### ISSUE TITLE
Event Model & API Endpoints

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#18]
**Overview**
We need to create the Mongoose Model and Express endpoints for the Events Data Model. This Event model will represent all volunteer opportunities that can be signed up for. 

**Tasks**
- [x] Determine necessary properties for Events
- [x] Create Mongoose Model
- [x] Create GET  ```/events/``` Endpoint
- [x] Create POST ```/events/``` Endpoint
- [x] Create GET ```/events/:eventId``` Endpoint
- [x] Create PUT ```/events/:eventId``` Endpoint
- [x] Create DELETE ```/events/:eventId``` Endpoint

**Acceptance Criteria** 

- Each endpoint should have proper field validation using [Express Validator](https://github.com/ctavan/express-validator) or a similar library. 
- Each endpoint should have appropriate query parameters (such as order: increasing/decreasing, limit, offset, etc.)
- Each endpoint should be [documented in the wiki](https://github.com/GTBitsOfGood/drawchange/wiki/API-Documentation)
