### ISSUE TITLE
User Model & RESTful Endpoints

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#19]
**Overview**
We need to create the Mongoose Model and Express endpoints for the User Data Model. This User model will represent all User (Volunteer/Manager/Admin) data

**Tasks**
- [x] Determine necessary properties for Users
- [x] Create Mongoose Model
- [x] Create GET  ```/users/``` Endpoint
- [x] Create POST ```/users/``` Endpoint
- [x] Create GET ```/users/:userId``` Endpoint
- [x] Create PUT ```/users/:userId``` Endpoint
- [x] Create DELETE ```/users/:userId``` Endpoint

**Acceptance Criteria** 

- Each endpoint should have proper field validation using [Express Validator](https://github.com/ctavan/express-validator) or a similar library. 
- Each endpoint should have appropriate query parameters (such as order: increasing/decreasing, limit, offset, etc.)
- Each endpoint should be [documented in the wiki](https://github.com/GTBitsOfGood/drawchange/wiki/API-Documentation)
