### ISSUE TITLE
Email Service Module

### ISSUE THREAD

**Issue by ahijaouy** [GTBitsOfGood/drawchange#20]
**Objective**
Create a Service Module that can be used to send emails. This module should contain all the core implementation logic to connect to an email sending library and expose a set of promise based functions that can be used to send emails. 

**Tasks**
- [x] Create & Expose a function that will allow you to send an email to a single email address. The email address, subject, and message body will be passed as strings. 
- [x] Create & Expose a function that will allow you to send the same email to many emails. The email addresses will be passed as an array of strings, and the message subject & body will be passed as strings. 
- [x] Modify the above functions to work with both plain text as well as HTML or markup (some sort of rich text)

**Acceptance Criteria**
- Each function that is exported from this module should contain a unit tests. Use [Mocha/Chai](https://hackernoon.com/how-to-run-mocha-chai-unit-tests-on-node-js-apps-832eb2eba590) to create these unit tests. 
- Each exported function should be [documented in the Wiki](https://github.com/GTBitsOfGood/drawchange/wiki/Email-Service-Module-Documentation). Internal functions may be explained in the wiki for clarity but are not necessary.
